### ISSUE TITLE
Block time to work OR inform me about bottlenecks

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/DPREP_spring_2024_group_4#14]
Hi all,

Your GitHub repository has been sitting "idle" since the last class. However, it is really important you adhere to the meeting vs. individual work schedule outlined in #5.

Can you please contact me today to explain where you're struggling? Is it about Git/GitHub? Or finding time to work on this? 

I need to understand how to support you best.

__Deliverable__:
- Plan individual and group time to work on this project, and block this time in your agendas, OR
- Contact me today during the coaching session to explain where you are struggling so that I can help you.

**Comment by RolfJens** [comment]
We worked on all the previous issues from week 3. We also scheduled a team-meeting for monday 04-03-24 to assign individual issues to each team member. We will discuss this individual issues at the team-meeting after that, which is scheduled during the coaching session on thursday 07-03-24.
