### ISSUE TITLE
Preparing for Migration of Files to GitHub

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/DPREP_spring_2024_group_4#3]
## Organize Files on Cloud Storage

Before we transition our work to GitHub, it's essential to consolidate and organize all the files we've worked on so far. This step will ensure that we have everything we need in one place and that our repository remains clean and manageable.

### Objective:

**Gather and organize project files on a cloud storage platform (Google Drive, Dropbox, or OneDrive).**

### Deliverable:

After completing the file organization, please **close this issue** and write a brief note detailing what types of files were deleted and any other organizational steps you took. This note will help us keep track of the cleanup process and ensure that only necessary files are migrated to GitHub.

### Instructions:

1. **Choose a Cloud Storage Platform:** Select either Google Drive, Dropbox, or OneDrive to gather all project-related files. This platform will serve as our temporary staging area for file organization. 

2. **File Consolidation:**
   - Create a new folder specifically for this project.
   - Upload all relevant files you've worked on so far into this folder.
   - Carefully go through these files and delete any that are no longer needed or relevant to the project's current scope.

3. **File Organization:**
   - Within the project folder, create sub-folders to categorize files logically (e.g., documentation, source code, data).
   - Ensure that all files are correctly named and placed in the appropriate sub-folders.

### Next Steps:

With your files organized and ready, you'll be set to start the migration process to GitHub, which will be outlined in the next issue.

**Comment by MSvanTergouw** [comment]
We cleaned the repository and started over with the issues of week 3, after updating the research question in the readme of the main branche.
